# Generated by Django 3.1.2 on 2020-11-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='before_account',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='profit_percent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_profit',
            field=models.FloatField(default=0),
        ),
    ]
