# Generated by Django 3.1.2 on 2020-10-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ergate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='stock_num',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
