# Generated by Django 3.1.2 on 2020-11-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ergate', '0003_auto_20201113_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
