# Generated by Django 3.1.2 on 2020-11-16 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ergate', '0004_simulation_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoset',
            name='auto_num',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='simul_num',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='stock_num',
            field=models.AutoField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
