# Generated by Django 3.1.2 on 2020-11-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ergate', '0005_auto_20201116_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='stock_num',
            field=models.IntegerField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
